const {execConfig} = require('./database');
const {toUSD} = require('./helpers');

exports.langPattern = () => {
    return new Promise(async(res, rej) => {
        let cfg = await execConfig();
        return res({
            'ru' : {
                viavk : 'Войти через VK',
                rgiveaway: {
                    title: 'Раздача',
                    t: 'Ежедневная раздача (каждый час)',
                    money: '5 рублей',
                    ul: '<li>Быть онлайн на сайте</li><li>За неделю пополнить 100 рублей</li><li>Быть подписаным на группы ВКонтакте <a href="https://vk.com/ebabkivk" target="_blank">Группа 1</a> <a href="https://vk.com/ebaboi" target="_blank">Группа 2</a> <a href="https://vk.com/ebasmeh" target="_blank">Группа 3</a></li><li>Система случайным образом выбирает 5 победителей и начисляет им 5 рублей на баланс.</li>',
                    btn: 'Принять участие',
                    btn2: 'Подождите..'
                },
                leftbar : {
                    jackpot : 'Режим Jackpot',
                    crash : 'Режим Crash',
                    dice : 'Режим Dice',
                    deposit : 'Пополнить баланс',
                    withdraw : 'Вывод средств',
                    send : 'Перевод средств',
                    pay_history : 'История счета',
                    ref : 'Реф.программа',
                    logout : 'Выход',
                    fair : 'Проверка честности',
                    youtube : 'Для ютуберов',
                    bonus : 'Ежедневный бонус',
                    faq : 'FAQ',
                    support : 'Поддержка',
                    terms : 'Соглашение',
                    shop : 'Магазин',
                    vgo : 'VGO Депозит'
                },
                topbar : {
                    online : 'Онлайн: ',
                    vk : 'ГРУППА ВК',
                    deposit : 'Пополнить баланс'
                },
                rightbar : {
                    chat : 'Чат игроков',
                    chat_placeholder : 'Введите текст сообщения'
                },
                jackpot : {
                    forgame : 'До начала',
                    bank : 'Банк игры',
                    history : 'История игр',
                    bet_info : 'Сделай ставку и получи возможность выиграть Джекпот',
                    bet_placeholder : 'Введите сумму',
                    balance : 'Ваш баланс: ',
                    bet_button : 'Сделать ставку',
                    bet_button_wait : 'Подождите..',
                    users : 'Игроки',
                    hash : 'HASH: ',
                    placed : 'поставил',
                    ticket : 'Билет: ',
                    won : 'Победил',
                    wticket : 'Билет',
                    winamount : 'Выигрыш'
                },
                jackpot_history : {
                    title : 'История игр (Сегодня)',
                    winner : 'Победитель',
                    won : 'Выигрыш',
                    ticket : 'Билет',
                    chance : 'Шансы',
                    action : 'Действия',
                    fair : 'Проверить',
                    fair_wait : 'Проверяем..',
                    resultnumber : 'Номер игры',
                    resultvalue : 'Победное число'
                },
                crash : {
                    autowithdraw : 'Автовывод',
                    autowithdraw_placeholder : 'Введите коэффициент',
                    bet : 'Введите ставку',
                    bet_placeholder : 'От 10 монет',
                    bet_all : 'Всё',
                    bet_button : 'Поставить',
                    bet_button_wait : 'Ставим..',
                    mybets : {
                        sum : 'Сумма ставки',
                        autowithdraw : 'Автовывод',
                        withdraw : 'Вывод',
                        cancel_button : 'Отменить',
                        cancel_button_wait : 'Отменяем..',
                        withdraw_button : 'Забрать',
                        withdraw_button_wait : 'Забираем..'
                    },
                    bets : {
                        title : 'Ставки игроков',
                        user : 'Пользователь',
                        bet : 'Ставка',
                        win : 'Выигрыш'
                    }
                },
                dice : {
                    balance : 'Ваш баланс',
                    bet_label : 'Введите ставку',
                    bet_placeholder : 'От ' + cfg.dice_min_bet + ' монет',
                    bet_all : 'Всё',
                    win_label : 'Возможный выигрыш',
                    multiplier_label : 'Множитель',
                    chance_label : 'Шанс на победу',
                    games_label : 'Всего игр',
                    sum_label : 'Сумма ставок сегодня',
                    bet_button : 'Сделать ставку',
                    bet_button_wait : 'Бросаем кости..',
                    hash : 'HASH: ',
                    last_games : 'Последние игры',
                    games : {
                        user : 'Игрок',
                        bet : 'Ставка',
                        number : 'Число',
                        multiplier : 'Выплата',
                        chance : 'Шанс',
                        won : 'Выигрыш',
                        action : 'Действия',
                        fair : 'Проверить'
                    }
                },
                fair : {
                    title : 'Проверка честности',
                    text : 'Как это работает?',
                    text2 : 'Вставте Ваш хэш в поле и проверьте результат, после расшифровки хэша вы получите победное число.',
                    hash : 'Введите ваш хэш',
                    fair : 'Проверить'
                },
                youtube : {
                    title : 'Сотрудничество с нами',
                    t1 : 'У вас есть свой <span>YouTube</span> канал ?',
                    tdesc : 'Получайте дополнительные возможности на ' + cfg.sitename,
                    b1title : 'Приемущества сотрудничества',
                    b1t1 : 'Возможность<br>ставить свой код<br>в партнерке',
                    b1t2 : 'Вывод без<br>комиссии',
                    b1t3 : 'Оплачиваемые<br>ролики и стримы',
                    b1t4 : 'Коды для<br>розыгрышей',
                    need : 'ГЛАВНОЕ ТРЕБОВАНИЕ: КАНАЛ YOUTUBE ОТ 1000 ПОДПИСЧИКОВ',
                    send : 'НАПИСАТЬ НАМ',
                    ny : 'Обязанности ютубера',
                    b2t1 : 'Выкладывать видео<br>раз в неделю',
                    b2t2 : 'Делать стрим раз<br>в неделю',
                    b2t3 : 'Размещать ссылку под<br>каждым роликом'
                },
                bonus : {
                    title : 'Бесплатные монеты',
                    desc : 'Получить бонус можно 1 раз в 24 часа.',
                    desc2 : 'Для получения ежедневного бонуса Вам неодходимо выполнить следующие условия:',
                    p1 : '1. Подписаться на наши группы ВК, <b><a href="https://vk.com/ebabkivk" target="_blank">Группа 1</a> <a href="https://vk.com/ebaboi" target="_blank">Группа 2</a> <a href="https://vk.com/ebasmeh" target="_blank">Группа 3</a></b><br>2. Сделать репост поста вк, <b><a target="_blank" href="'+cfg.vkpost+'">ссылка</a></b><br>3. Разрешите группе писать вам',
                    check : 'Проверить',
                    check_wait : 'Проверяем..'
                },
                faq  : {
                    q1 : 'КАК ПОПОЛНИТЬ БАЛАНС С ПОМОЩЬЮ БАНКОВСКОЙ КАРТЫ / YANDEX / WEBMONEY / QIWI И ДРУГИЕ?',
                    a1 : 'Слева в меню или наверху около баланса есть кнопка "Пополнить баланс".<br>Там доступно более 12 платежных направлений.',
                    q2 : 'НЕ ПРИШЛИ ДЕНЬГИ ПОСЛЕ ПОПОЛНЕНИЯ',
                    a2 : 'Если вы оплачивали через QIWI то нужно немного подождать, пополнение занимает до 5 минут.<br>Если вы пополняли баланс что-то пошло не так, то напишите нам в группу, мы поможем :)',
                    q3 : 'ДЕПОЗИТ ДЛЯ ВЫВОДА',
                    a3 : 'Для вывода средств необходим минимальный депозит в '+cfg.dep_before_withdraw+' рублей. <br> Это сделано для защиты от фейковых аккаунтов.',
                    q4 : 'ВЫВОД ОТМЕНЯЕТСЯ',
                    a4 : 'Запрещено выводить, не умножив или разделив сумму последнего пополения хотя бы в 1.5 раза.<br>Пример : пополнили на 1000 монеток, для вывода нужно как минимум поднять баланс до 1500 монеток или слить до 500 монеток.<br>Эта система создана для защиты сайта против людей, использующие вывод в качестве обменника.'
                },
                support  : {
                    title : 'Поддержка',
                    q1 : 'Заявки на модератора',
                    a1 : 'Мы не ищем модераторов, если не указано иное. Если вы заинтересованы в том, чтобы подать заявку на должность модератора, вам нужно сначала быть активным и полезным в чате в течение значительного времени.',
                    q2 : 'Спонсорство',
                    a2 : 'Мы требуем как минимум 4000+ подписчиков на YouTube и 4000+ просмотров в среднем на видео для сотрудничества. Мы добавляем реферальный код в whitelist , только если у вас есть значительный охват аудитории в социальных сетях или на Youtube. Если вы запрашиваете партнерство \ реферальный код и не отвечаете вышеуказанным требованиям, мы не будем отвечать на ваш email.',
                    q3 : 'Поддержка',
                    a3 : 'Если вы отправляете запрос в нашу техническую поддержку, пожалуйста всегда добавляйте к нему ваш UserID, скриншоты и любую другу важную информацию.',
                    q4 : 'Контакты',
                    a4 : 'Поддержка: <a class="mailto" href="mailto:support@ebabki.com">support@ebabki.com</a>',
                    a4_1 : 'Поддержка VK: <a class="mailto" href="'+cfg.vkgroup+'">VK.com</a>'
                },
                langs : {
                    ru : 'Русский',
                    en : 'Английский'
                },
                permissions : {
                    admin : 'Администратор',
                    moder : 'Модератор',
                    vip : 'Вип',
                    youtube : `Ютубер`
                },
                titles : {
                    auth : 'Авторизация',
                    load : 'Загрузка..'
                },
                alerts : {
                    notfound : 'Не удалось найти страницу, которую вы запрашиваете!',
                    autherror : 'Ошибка при проверке состояния авторизации!',
                    captcha : 'Вы не ввели капчу!',
                    notlogin : 'Вы не ввели логин!',
                    notpass : 'Вы не ввели пароль!',
                    notpass2 : 'Пароли не совпадают!',
                    whoops : 'Что-то пошло не так!',
                    send_vip : 'Перевод доступен только для вип игроков!',
                    trylater : 'Попробуйте чуть позже!',
                    hashwrong : 'Хэш указан неверно!',
                    alreadycheckhash : 'Результат этого хэша снизу!',
                    sendidwrong : 'Неверно введено ID получателя!',
                    sendsumwrong : 'Неверно введена сумма!',
                    crashbetwrong : 'Неверно введена сумма ставки!',
                    auth : 'Вы должны быть авторизованы!',
                    copy : 'Скопировано в буфер обмена!',
                    depositsumwrong : 'Вы не ввели сумму!',
                    minwithdraw : 'Минимальная сумма вывода с учетом комиссии - '+cfg.withdraw_min+' руб.',
                    withdrawwallet : 'Вы не указали номер кошелька!',
                    jackpotbetwrong : 'Сумма указана не верно!',
                    giveaway : 'Для запуска розыгрыша введите /give сумма  (Пример : /give '+cfg.giveaway_min+')',
                    wsclose : 'Соединение с сервером потеряно',
                    wsopen : 'Соединение с серверов восстановлено',
                    unauth : 'Неверный логин или пароль!'
                },
                giveaway : {
                    title : 'РОЗЫГРЫШ ОТ:',
                    price : 'НА СУММУ:',
                    t1 : 'Угадай число от 1 до ',
                    t2 : ' и получи монеты!'
                },
                deposit : {
                    title : 'Обратите внимание:',
                    desc : 'Депозит средств производится на платежные системы указанные ниже. <br> Средства поступят на счет в течении 5-ти минут с момента оплаты',
                    t1 : '1.ВЫБЕРИТЕ ПЛАТЕЖНУЮ СИСТЕМУ:',
                    t2 : '2.ВВЕДИТЕ СУММУ',
                    placeholder : 'Сумма в рублях',
                    comission : 'Комиссия',
                    finaly : 'Итог к оплате :',
                    btn : 'Внести',
                    btn2 : 'Подождите'
                },
                withdraw : {
                    title : 'Обратите внимание:',
                    desc : 'Вывод средств производится на платежные системы указанные ниже.<br>Пожалуйста, учтите, если вы неверно ввели платежные реквизиты средства не возращаются.<br>Вывод осуществляется в течении 24 часов',
                    d1 : 'Минимальная сумма для вывода - <span id="min_wid">'+cfg.withdraw_min+'</span> рублей',
                    d2 : 'Вывод разрешен только после пополнения на '+cfg.dep_before_withdraw+' руб!',
                    awailable : 'Доступно для вывода:',
                    t1 : '1.ВЫБЕРИТЕ ПЛАТЕЖНУЮ СИСТЕМУ:',
                    t2 : '2.ВВЕДИТЕ СУММУ И ВАШ НОМЕР СЧЁТА',
                    placeholder : 'Сумма в рублях',
                    comission : 'Комиссия',
                    finaly : 'Итог к получению:',
                    str : 'Я подтверждаю правильность введенных данных',
                    btn : 'Вывести средства',
                    btn2 : 'Подождите..'
                },
                send : {
                    title : 'Перевод монет',
                    myid : 'Ваш уникальный ID',
                    t1 : '<b>Для перевода монет игроку достаточно знать его уникальный ID</b>',
                    t2 : 'Минимальная сумма перевода '+cfg.send_min+' монет<br>Для выполнения перевода нужно сделать вывод минимум на '+cfg.dep_before_send+' рублей',
                    label1 : 'Введите ID получателя',
                    label2 : 'Введите сумму перевода',
                    total : 'Будет списано:',
                    comission : 'комиссия',
                    btn : 'Подтвердить перевод',
                    btn2 : 'Отправляем..'
                },
                ref : {
                    title : 'Реферальная программа',
                    t1 : 'Для получения личного реферального кода необходимо:',
                    d1 : '1. Подписаться на нашу группу ВК, <b><a href="https://vk.com/ebabkivk" target="_blank">Group 1</a> <a href="https://vk.com/ebaboi" target="_blank">Group 2</a> <a href="https://vk.com/ebasmeh" target="_blank">Group 3</a></b><br>2. Сделать репост поста вк, <b><a target="_blank" href="'+cfg.vkpost+'">ссылка</a></b><br>3. Разрешите группе писать вам',
                    cbtn : 'Проверить',
                    cbtn2 : 'Проверяем..',
                    d2 : 'Приглашай друзей и знакомых, играй с ними и зарабатывай вместе!<br>Если ваш друг введет код, он получит бесплатные монетки для проверки сайта. А вы будете получать 1 монет с каждого приглашенного друга.',
                    copy : 'СКОПИРОВАТЬ',
                    t2 : 'Вас пригласили ? или есть промокод ?',
                    d3 : 'Вводите сюда реф код или и получите монеты бесплатно.',
                    abtn : 'АКТИВИРОВАТЬ',
                    abtn2 : 'АКТИВИРУЕМ..',
                    t4 : 'Статистика заработка',
                    d4t1 : 'Вы пригласили',
                    d4t2 : 'чел. и получили',
                    d4t3 : 'руб. с их пополнений',
                    t5 : 'Информация о заработке',
                    rname : 'рефералов',
                    percent : 'от пополнений',
                    label : 'Ваш промокод'
                },
                phistory : {
                    title1 : 'Активные выводы',
                    t1 : {
                        t1 : 'Дата',
                        t2 : 'Система<br>Кошелек',
                        t3 : 'Сумма',
                        t4 : 'Действия'
                    },
                    title2 : 'История пополнений',
                    t2 : {
                        t1 : 'Дата',
                        t2 : 'Тип',
                        t3 : 'Система<br>Кошелек',
                        t4 : 'Сумма',
                        t5 : 'Статус'
                    },
                    title3 : 'История выводов',
                    status : {
                        success : 'Выполнен',
                        wait : 'Ожидается',
                        decline : 'Отклонен',
                        sending : 'Отправляется',
                        sent : 'Отправлен',
                        error : 'Ошибка',
                        accept : 'Одобрен',
                        check : 'На модерации', 
                        comp : 'Обрабатывается'
                    },
                    types : {
                        bonus : 'Бонус',
                        ref : 'Реф. программа',
                        promo : 'Промокод',
                        ref2 : 'Реферальный код',
                        another : 'Другая сис-ма',
                        withdraw : 'Вывод'
                    },
                    action : 'Действия',
                    nothing : 'Пусто',
                    btn1 : 'Отменить',
                    btn2 : 'Отменяем..',
                    vgo : 'VGO Депозит',
                    skins : 'Вывод предметов',
                    items : 'Предметы',
                    cost : 'Цена',
                    status2 : 'Статус',
                    game : 'Игра',
                    got : 'Забрать',
                    got2 : 'Забираем..'
                },
                vgo : {
                    title : 'VGO Депозит',
                    label : 'Введите свой steamid64',
                    btn1 : 'Загрузить инвентарь',
                    btn2 : 'Загружаем...',
                    btn3 : 'Внести'
                },
                terms : {
                    title : 'Соглашение',
                    t1 : 'Общие правила сайта',
                    b1 : '<li>Данный документ является договором на использование сервиса ' + cfg.sitename + '. Ниже приведены правила и условия использования Сервиса. Пожалуйста, внимательно ознакомьтесь с ними.</li><li>Сервисом могут пользоваться лица старше 18 лет.</li><li>Игра "' + cfg.sitename + '" - онлайн игра принадлежащая организатору и находящаяся по адресу в сети интернет ' + cfg.domain + '. Организатором предоставляются услуги пользователю по организации его развлечения, досуга и отдыха.</li><li>Организаторы  онлайн игры ' + cfg.sitename + ' никого насильно не заставляют проводить свой досуг на этом проекте.</li><li>Администрация Сервиса оставляет за собой право вносить изменения в текст данных Правил. Пользователь самостоятельно отслеживает изменения Правил, размещенных по адресу ' + cfg.domain + '/termslogin.</li>',
                    t2 : 'Учетная запись, пароль, безопасность.',
                    b2 : '<li>Для открытия Учетной Записи пользователь должен авторизоваться через Вконтакте.</li><li>Пользователь несет полную ответственность за хранение конфиденциальной информации, за потерю доступа к своей Учетной Записи.</li><li>Кроме того, пользователь несет полную ответственность за любые совершенные им действия.</li><li>Сервис не несет ответственности за поступки, совершенные Пользователем в отношении третьих лиц.</li><li>Пользователь обязуется сообщить Сервису о любом несанкционированном использовании его Учетной записи.</li>',
                    t3 : 'Конфиденциальность.',
                    b3 : '<li>Сервис обязуется не редактировать и не раскрывать любую конфиденциальную информацию, предоставленную Пользователем Сервису.</li><li>Сервис также обязуется хранить личный пароль пользователя в зашифрованном виде.</li><li>Личные данные могут быть предоставлены третьим лицам лишь в связи с нарушением законодательства, а также оскорблением или клеветой в отношении брендов или торговых марок третьих лиц.</li>',
                    t4 : 'Пользователь.',
                    b4 : '<li>Сервис оставляет за собой право в любой момент без предварительного оповещения блокировать Пользователя в связи с нарушением правил использования Сервиса или законодательства, а также аннулировать весь баланс, если это финансовое нарушение.</li><li>Неприемлемы попытки несанкционированного доступа, попытки нанесения вреда Сервису.</li><li>При добавлении на сайт любой информации, запрещены оскорбления, вымогательства, клевета, блеф, сообщения, содержащие вредоносную информацию (в т.ч. вирусы, трояны, черви и т.п.), а также информация, способная нанести вред третьим лицам.</li>',
                    t5 : 'Запрещено.',
                    b5 : '<li>Запрещается публиковать фальсифицированные данные</li><li>Запрещается передача любых материалов, которые могут нарушить интеллектуальную собственность третьих лиц.</li><li>Запрещаются фальшивые публикации информации с целью получения несанкционированных доступов к информации или данным третьих лиц.</li><li>Запрещается использование различных тактик и схем с целью получить выгоду.</li><li>Запрещается регистрировать более одной Учетной Записи.</li><li>Запрещается использовать нецензурную лексику, оскорблять других участников и обвинять сайт в мошеничестве.</li><li>Запрещается пополнять счет на сайте с целью вывода денежных средств на другую платежную систему.</li><li>Запрещается передавать данные для доступа к Учетной записи третьим лицам.</li><li>Запрещается оскорблять, обзывать, ставить под сомнение профессиональную квалификацию и добросовестность физических и юридических лиц, в том числе Пользователей Сервиса и Администрации Сервиса.</li><li>Запрещается выбирать себе аватары, содержащие сцены насилия, угрозы, сквернословия, разврат (порнография), дискриминация в любых проявлениях, коммерческая реклама и рекламные тексты.</li><li>Запрещается несанкционированное воздействие на сервер и (или) код игры.</li><li>Запрещается создание и запуск несанкционированного Администрацией бота или иной автоматизированной (полуавтоматизированной) программы с целью совершения любых действий.</li><li>Запрещается выводить, не умножив или разделив сумму последнего пополения хотя бы в 1.5 раза.</li>',
                    t6 : 'Выплаты.',
                    b6 : '<li>Выплаты производятся в ручном режиме.</li><li>Запрещено выводить, не умножив или разделив сумму последнего пополения хотя бы в 1.5 раза.</li><li>При выводе бонусных рублей может быть отказано без всяких причин.</li><li>Администрация сайта может потребовать скан или фото паспорта для верификации.</li><li>При отказе предоставить дополнительную информацию или верификации кошелька аккаунт может быть заблокирован.</li><li>При нарушении правил баланс аккаунта может быть списан.</li>',
                    t7 : 'Соглашение с правилами сайта (оферты).',
                    b7 : '<li>Зарегистрировавшись в Сервисе, Вы, тем самым, соглашаетесь с правилами нашего сайта.</li>',
                    t8 : 'Права.',
                    b8 : '<li>Исключительное право на Сервис принадлежит Сервису.</li><li>Все права на материалы, представленные на нашем сайте, принадлежат Правообладателям.</li>'
                },
                lvl : {
                    t1 : 'Ваш уровень:',
                    t2 : 'Уровень',
                    toup : 'До повышения уровня нужно пополнить на: '
                },
                skins : {
                    title : 'Вывод скинами',
                    list : 'Товары',
                    hl : 'От дорогих к дешевым',
                    lh : 'От дешевых к дорогим',
                    all : 'Все',
                    total : 'Всего',
                    buy : 'Купить',
                    buy2 : 'Покупаем..',
                    search : 'Введите текст для поиска',
                    trade1 : 'Введите ссылку на обмен Steam',
                    trade2 : 'Введите SteamID64 аккаунта, на котором вы используете OPSkins',
                    realTrade : 'Введите адрес доставки',
                    more : 'Загрузить еще',
                    accept : 'Подтвердить',
                    wait : 'Подождите..',
                    send_info: 'Информация для отправки',
                    send_info2: 'Введите корректные данные, в противном случае Вы не сможете получить товар!',
                    fio: 'ФИО',
                    fio2: 'Фамилия Имя Очество',
                    adres: 'Адрес доставки',
                    index: 'Почтовый индекс',
                    index2: 'Индекс',
                    phone: 'Контактный телефон',
                    phone2: 'Телефон'
                },
                auth : {
                    auth : 'Вход',
                    reg : 'Регистрация',
                    login : 'Логин',
                    password : 'Пароль',
                    password2 : 'Повторить пароль',
                    authbtn : 'Войти',
                    regbtn : 'Зарегистрироваться',
                    wait : 'Подождите..',
                    t : 'ВОЙТИ ЧЕРЕЗ СОЦИАЛЬНЫЕ СЕТИ',
                    d1 : 'Авторизуясь вы потдверждаете,что вам есть 18 лет и принимаете условия <a href="/termslogin" rel="popup" target="_blank" style="color: #4348887d;"> пользовательского соглашения.',
                    d2  : '*УСЛУГИ САЙТА – ЯВЛЯЮТСЯ ИМИТАТОРОМ (СИМУЛЯТОРОМ), ПОЗВОЛЯЮЩИМ ПОЛУЧИТЬ ПСИХО-ЭМОЦИОНАЛЬНОЕ УДОВЛЕТВОРЕНИЕ БЕЗ КАКИХ БЫ ТО НИ БЫЛО РИСКОВ ДЛЯ ПОЛЬЗОВАТЕЛЯ, В СВЯЗИ С ЧЕМ, УСЛУГИ САЙТА ОТНОСЯТСЯ К АТТРАКЦИОННЫМ.'
                }
            },
            'en' : {
                viavk : 'Login via VKontakte',
                rgiveaway: {
                    title: 'Giveaway',
                    t: 'Daily bonus (every hour)',
                    money: await toUSD(5, 2) + ' USD',
                    ul: '<li>Be online on the site</li><li>Deposit '+(await toUSD(100,2))+' USD per week</li><li>To subscribe to VKontakte groups: <a href="https://vk.com/ebabkivk" target="_blank">Group 1</a> <a href="https://vk.com/ebaboi" target="_blank">Group 2</a> <a href="https://vk.com/ebasmeh" target="_blank">Group 3</a></li><li>Allow group write to you<div id="vk_allow_messages_from_community"></div></li><li>The system randomly selects 5 winners and charges them '+(await toUSD(5,2))+' USD to the balance.</li>',
                    btn: 'Participate',
                    btn2: 'Please wait..'
                },
                leftbar : {
                    jackpot : 'Jackpot',
                    crash : 'Crash',
                    dice : 'Dice',
                    deposit : 'Deposit',
                    withdraw : 'Withdraw',
                    send : 'Money transaction',
                    pay_history : 'Pay History',
                    ref : 'Referral ',
                    logout : 'Logout',
                    fair : 'Fair play',
                    youtube : `For YouTuber's`,
                    bonus : 'Daily bonus',
                    faq : 'FAQ',
                    support : 'Support',
                    terms : 'Terms',
                    shop : 'Shop',
                    vgo : 'VGO Deposit'
                },
                topbar : {
                    online : 'Online: ',
                    vk : 'VK GROUP',
                    deposit : 'Deposit'
                },
                rightbar : {
                    chat : 'Chat',
                    chat_placeholder : 'Enter your message'
                },
                jackpot : {
                    forgame : 'Begin at',
                    bank : 'Game bank',
                    history : 'Games history',
                    bet_info : 'Place your bet and get the chance to win the jackpot',
                    bet_placeholder : 'Enter amount',
                    balance : 'Your balance:',
                    bet_button : 'Place a bet',
                    bet_button_wait : 'Please wait..',
                    users : 'Players',
                    hash : 'HASH: ',
                    placed : 'Bet: ',
                    ticket : 'Tickets: ',
                    won : 'Winner',
                    wticket : 'Ticket',
                    winamount : 'Won'
                },
                jackpot_history : {
                    title : 'Game History (Today)',
                    winner : 'Winner',
                    won : 'Win',
                    ticket : 'Ticket',
                    chance : 'Chance',
                    action : 'Actions',
                    fair : 'Check fair'
                },
                crash : {
                    autowithdraw : 'Auto Withdraw',
                    autowithdraw_placeholder : 'Enter the coefficient',
                    bet : 'Enter a bet',
                    bet_placeholder : 'From ' + (await toUSD(cfg.crash_min_bet, 2)),
                    bet_all : 'All',
                    bet_button : 'Place',
                    bet_button_wait : 'Please wait..',
                    mybets : {
                        sum : 'Bet Amount',
                        autowithdraw : 'Autowithdraw',
                        withdraw : 'Withdraw',
                        cancel_button : 'Cancel',
                        cancel_button_wait : 'Canceling..',
                        withdraw_button : 'Withdraw',
                        withdraw_button_wait : 'Withdraw..'
                    },
                    bets : {
                        title : 'Players bets',
                        user : 'User',
                        bet : 'Amount',
                        win : 'Won'
                    }
                },
                dice : {
                    balance : 'Your balance',
                    bet_label : 'Enter a bet',
                    bet_placeholder : 'From ' + (await toUSD(cfg.dice_min_bet, 2)),
                    bet_all : 'All',
                    win_label : 'Possible win',
                    multiplier_label : 'Multiplier',
                    chance_label : 'Chance to win',
                    games_label : 'Total games',
                    sum_label : 'Bet amount today',
                    bet_button : 'Place a bet',
                    bet_button_wait : 'Please wait..',
                    hash : 'HASH: ',
                    last_games : 'Last games',
                    games : {
                        user : 'User',
                        bet : 'Amount',
                        number : 'Number',
                        multiplier : 'Multiplier',
                        chance : 'Chance',
                        won : 'Win',
                        action : 'Actions',
                        fair : 'Check fair'
                    }
                },
                fair : {
                    title : 'Fair play',
                    text : 'How it works?',
                    text2 : 'Insert your hash in the field and check the result, after decrypting the hash you will receive a winning number.',
                    hash : 'Enter your hash',
                    fair : 'Check fair',
                    fair_wait : 'Please wait..',
                    resultnumber : 'Game ID',
                    resultvalue : 'Victory number'
                },
                youtube : {
                    title : 'Cooperation with us',
                    t1 : 'Do you have your <span>YouTube</span> channel?',
                    tdesc : 'Get more features on ' + cfg.sitename,
                    b1title : 'Benefits of cooperation',
                    b1t1 : 'Opportunity to put your code in affiliate program',
                    b1t2 : 'Withdrawal without commission',
                    b1t3 : 'Paid videos and streams',
                    b1t4 : 'Codes for giveaway',
                    need : 'MAIN REQUIREMENT: YOUTUBE CHANNEL FROM 1000 SUBSCRIBERS',
                    send : 'WRITE TO US',
                    ny : 'Responsibilities of YouTube`rs',
                    b2t1 : 'Upload videos<br>once a week',
                    b2t2 : 'Stream once<br>a week',
                    b2t3 : 'Post link with<br>each video'
                },
                bonus : {
                    title : 'Free coins',
                    desc : 'You can get a bonus 1 time per 24 hours.',
                    desc2 : 'To receive a daily bonus you need to fulfill the following conditions:',
                    p1 : '1. Subscribe to all VK groups, <b> <a href="https://vk.com/ebabkivk" target="_blank">Group 1</a> <a href="https://vk.com/ebaboi" target="_blank">Group 2</a> <a href="https://vk.com/ebasmeh" target="_blank">Group 3</a> </b> <br> 2. Make a repost post vk, <b> <a target="_blank" href="'+cfg.vkpost+'"> link </a> </b> <br> 3. Allow group write to you',
                    check : 'Get',
                    check_wait : 'Please wait..'
                },
                faq  : {
                    q1 : 'HOW TO FILL UP BALANCE WITH THE BANK CARD / YANDEX / WEBMONEY / QIWI AND OTHERS?',
                    a1 : 'On the left in the menu or at the top of the balance there is a button "Deposit funds."',
                    q2 : "DON'T GET MONEY AFTER REPLENISHMENT",
                    a2 : 'If you paid through QIWI, then you need to wait a bit, the replenishment takes up to 5 minutes. <br> If you replenished the balance something went wrong, then write to us in the group, we will help :)',
                    q3 : 'DEPOSIT FOR CASHOUT',
                    a3 : 'To withdraw the required minimum deposit of 100 rubles. <br> This is done to protect against fake accounts.',
                    q4 : 'OUTPUT CANCELED',
                    a4 : 'It is forbidden to withdraw without multiplying or dividing the amount of the last deposit at least 1.5 times. <br> Example: replenished by 1000 coins, for withdrawal, you need to at least raise the balance to 1500 coins or drain to 500 coins. <br> This system is designed to protect site against people using withdrawal as an exchanger.'
                },
                support  : {
                    title : 'Support',
                    q1 : 'Moderator Applications',
                    a1 : 'We are not looking for moderators unless otherwise declared. If you are interested in applying for a moderator position, you need to first be active and helpful in the chat for a considerable amount of time.',
                    q2 : 'Sponsorship',
                    a2 : 'We Require at least 4000+ Youtube Subscribers and 4000+ average views per video for a sponsorship. We only whitelist people`s referral code if they have a considerable social media or Youtube following. If you ask for a sponsorship/referral code and do not meet the above requirements, we will not respond to your email.',
                    q3 : 'Support',
                    a3 : 'If you have a request or concern directed at our Support, please always provide your UserID and screenshots or otherwise relevant information.',
                    q4 : 'Contacts',
                    a4 : 'Support: <a class="mailto" href="mailto:support@ebabki.com">support@ebabki.com</a>',
                    a4_1 : 'Support VK: <a class="mailto" href="https://vk.com">VK.com</a>'
                },
                langs : {
                    ru : 'Russian',
                    en : 'English'
                },
                permissions : {
                    admin : 'Admin',
                    moder : 'Moder',
                    vip : 'Vip',
                    youtube : `YouTube`
                },
                titles : {
                    auth : 'Sign In',
                    load : 'Loading..'
                },
                alerts : {
                    notfound : 'Could not find the page you are requesting!',
                    autherror : 'Error while checking authorization status!',
                    captcha : 'You have not entered a captcha!',
                    notlogin : 'You have not entered a login!',
                    notpass : 'You have not entered a password!',
                    notpass2 : 'Passwords do not match!',
                    whoops : 'Something went wrong!',
                    send_vip : 'Money transactions is available only for VIP players!',
                    trylater : 'Try a little later!',
                    hashwrong : 'The hash is invalid!',
                    alreadycheckhash : 'The result of this hash below!',
                    sendidwrong : 'Invalid recipient ID!',
                    sendsumwrong : 'Invalid amount entered!',
                    crashbetwrong : 'Invalid bet amount!',
                    auth : 'You must be logged in!',
                    copy : 'Copied to clipboard!',
                    depositsumwrong : 'You have not entered the amount!',
                    minwithdraw : 'Minimum withdrawal amount including commission is '+(await toUSD(cfg.withdraw_min, 2))+' USD.',
                    withdrawwallet : 'You did not specify the wallet number!',
                    jackpotbetwrong : 'The amount indicated is not true!',
                    giveaway : 'To start the giveaway enter /give amount (Example: /give '+cfg.giveaway_min+')',
                    wsclose : 'Server connection lost',
                    wsopen : 'Server connection restored',
                    unauth : 'Wrong login or password!'
                },
                giveaway : {
                    title : 'GIVEAWAY BY:',
                    price : 'AMOUNT:',
                    t1 : 'Guess the number from 1 to ',
                    t2 : ' and get coins!'
                },
                deposit : {
                    title : 'Note:',
                    desc : 'A deposit of funds is made on the payment systems listed below. <br> Funds will be credited to your account within 5 minutes from the date of payment.',
                    t1 : '1. SELECT A PAYMENT SYSTEM:',
                    t2 : '2. ENTER THE SUM ($)',
                    placeholder : 'Dollar amount',
                    comission : 'Commission',
                    finaly : 'Total for payment:',
                    btn : 'Deposit',
                    btn2 : 'Please wait..'
                },
                withdraw : {
                    title : 'Note:',
                    desc : 'Withdrawals are made to the payment systems listed below. <br> Please note that if you have entered the payment details incorrectly, the funds will not be returned. <br> Withdrawals are made within 24 hours',
                    d1 : 'The minimum amount for withdrawal - <span id = "min_wid"> ' + (await toUSD(cfg.withdraw_min, 2)) + ' </ span> USD',
                    d2 : 'The withdrawal is allowed only after replenishing '+ (await toUSD(cfg.dep_before_withdraw, 2)) +' USD!',
                    awailable : 'Available for withdrawal:',
                    t1 : '1. SELECT A PAYMENT SYSTEM:',
                    t2 : '2. ENTER THE SUM AND YOUR ACCOUNT NUMBER',
                    placeholder : 'Dollar amount',
                    comission : 'Commission',
                    finaly : 'Total receivable:',
                    str : 'I confirm the correctness of the entered data',
                    btn : 'Withdraw',
                    btn2 : 'Please wait..'
                },
                send : {
                    title : 'Money transfer',
                    myid : 'Your unique ID',
                    t1 : '<b>To transfer coins, it’s enough for a player to know his unique ID </ b>',
                    t2 : 'The minimum transfer amount is ' + (await toUSD(cfg.send_min, 2)) + ' USD <br> To complete a transfer, you need to make a withdrawal of at least ' + (await toUSD(cfg.dep_before_send, 2)) + ' USD',
                    label1 : 'Enter recipient ID',
                    label2 : 'Enter the transfer amount ($)',
                    total : 'Cost:',
                    comission : 'commission',
                    btn : 'Confirm transfer',
                    btn2 : 'Sent..'
                },
                ref : {
                    title : 'Referral program',
                    t1 : 'To obtain a personal referral code, you must:',
                    d1 : '1. Subscribe to our VK group, <b> <a href="https://vk.com/ebabkivk" target="_blank">Group 1</a> <a href="https://vk.com/ebaboi" target="_blank">Group 2</a> <a href="https://vk.com/ebasmeh" target="_blank">Group 3</a> </b> <br> 2. Make a repost post vk, <b> <a target="_blank" href="'+cfg.vkpost+'"> link </a> </b> <br> 3. Allow group write to you',
                    cbtn : 'Check',
                    cbtn2 : 'Please wait..',
                    d2 : 'Invite your friends and acquaintances, play with them and earn money together! <br> If your friend enters the code, he will receive free coins to check the site. And you will receive 1 coins from each invited friend.',
                    copy : 'COPY',
                    t2 : 'Have you been invited? Or is there a promo code?',
                    d3 : 'Enter here the ref code or get coins for free.',
                    abtn : 'ACTIVATE',
                    abtn2 : 'ACTIVATE..',
                    t4 : 'Earnings statistics',
                    d4t1 : 'You invited',
                    d4t2 : 'people(s). and get',
                    d4t3 : 'USD from their deposits',
                    t5 : 'Earnings information',
                    rname : 'referrals',
                    percent : '/ dep',
                    label : 'Your code'
                },
                phistory : {
                    title1 : 'Active withdraws',
                    t1 : {
                        t1 : 'Date',
                        t2 : 'System<br>Wallet',
                        t3 : 'Amount',
                        t4 : 'Actions'
                    },
                    title2 : 'Deposit history',
                    t2 : {
                        t1 : 'Date',
                        t2 : 'Type',
                        t3 : 'System<br>Wallet',
                        t4 : 'Amount',
                        t5 : 'Status'
                    },
                    title3 : 'Withdraw history',
                    status : {
                        success : 'Done',
                        wait : 'Pending',
                        decline : 'Canceled',
                        sending : 'Sending',
                        sent : 'Sent',
                        error : 'Error',
                        accept : 'Accept',
                        check : 'Moderation',
                        comp : 'Processed'
                    },
                    types : {
                        bonus : 'Bonus',
                        ref : 'Ref. program',
                        promo : 'Promo code',
                        ref2 : 'Referral code',
                        another : 'Other system',
                        withdraw : 'Cashout'
                    },
                    action : 'Actions',
                    nothing : 'Clear',
                    btn1 : 'Cancel',
                    btn2 : 'Canceling..',
                    vgo : 'VGO Deposit',
                    skins : 'Skins cashout',
                    items : 'Items',
                    cost : 'Price',
                    status2 : 'Status',
                    game : 'Game',
                    got : 'Send',
                    got2 : 'Sending..'
                },
                vgo : {
                    title : 'VGO Deposit',
                    label : 'Enter your steamid64',
                    btn1 : 'Get Inventory',
                    btn2 : 'Please wait..',
                    btn3 : 'Deposit'
                },
                terms : {
                    title : 'Terms',
                    t1 : 'General site rules',
                    b1 : '<li> This document is a contract to use the ' + cfg.sitename + ' service. Below are the terms and conditions of use of the Service. Please read them carefully. </li> <li> The service can be used by persons over 18. </li> <li> The game "' + cfg.sitename + '" is an online game owned by the organizer and located at the Internet address '+cfg.domain+'. The organizer provides services to the user on the organization of his entertainment, leisure and recreation. </li> <li> The organizers of the online game ' + cfg.sitename + ' do not force anyone to spend their leisure time on this project. </li> <li> The Service Administration reserves the right to make changes in the text of these Rules. The user independently tracks changes to the Rules posted at ' + cfg.domain + '/terms. </li>',
                    t2 : 'Account, password, security.',
                    b2 : '<li> To open an Account, the user must log in via Vkontakte. </li> <li> The user is fully responsible for storing confidential information, for losing access to his Account. </li> <li> In addition, the user is fully responsible responsible for any actions taken by him. </li> <li> The Service is not responsible for actions committed by the User against third parties. </li> <li> The User undertakes to inform the Service of any unauthorized use of his Account. </ li >',
                    t3 : 'Confidentiality.',
                    b3 : "<li> The Service undertakes not to edit or disclose any confidential information provided by the User to the Service. </li> <li> The Service also undertakes to store the user's personal password in encrypted form. </li> <li> Personal data may be provided to third parties only due to violation of the law, as well as insult or defamation of brands or trademarks of third parties. </li>",
                    t4 : 'User.',
                    b4 : '<li> The Service reserves the right to block the User at any time without prior notification due to a violation of the rules for using the Service or legislation, and also to cancel the entire balance if it is a financial violation. </li> <li> Unauthorized access attempts are not allowed. harming the Service. </li> <li> When adding any information to the site, it is forbidden to insult, extortion, slander, bluff, messages containing harmful information (including viruses, Trojans, worms, etc.), as well as information capable harm third parties. </li>',
                    t5 : 'Prohibited.',
                    b5 : '<li> It is forbidden to publish falsified data. </li> <li> It is forbidden to transmit any material that may violate the intellectual property of third parties. </li> <li> Fake publication of information is prohibited in order to obtain unauthorized access to information or data of third parties. </li> <li> It is forbidden to use different tactics and schemes in order to gain benefits. </li> <li> It is forbidden to register more than one Account. </li> <li> It is forbidden to use foul language, insult other participants and blame the site in mo Enjoyment. </li> <li> It is forbidden to replenish the account on the site in order to withdraw funds to another payment system. </li> <li> It is prohibited to transfer data for access to the Account to third parties. </li> <li> It is forbidden insult, call, challenge the professional qualifications and integrity of individuals and legal entities, including Service Users and Service Administration. </li> <li> It is forbidden to choose avatars that contain scenes of violence, threats, foul language, debauchery (pornography), discrimination of any kind advertising and advertising texts. </li> <li> The unauthorized impact on the server and / or the game code is prohibited. </li> <li> It is prohibited to create and launch an unauthorized bot administration or other automated (semi-automated) program to perform any action. </li> <li> It is forbidden to output without multiplying or dividing the sum of the last deposit at least 1.5 times. </li>',
                    t6 : 'Payouts.',
                    b6 : '<li> Payments are made in manual mode. </li> <li> It is forbidden to withdraw without multiplying or dividing the amount of the last deposit at least 1.5 times. </li> <li> When withdrawing bonus rubles, it can be denied for no reason. </li> <li> The site administration may require a scan or photo of the passport for verification. </li> <li> If you refuse to provide additional information or verification of the wallet, your account may be blocked. </li> <li> If you violate the rules of the account balance may be written off. </li>',
                    t7 : 'Agreement with the rules of the site (offer).',
                    b7 : '<li> By registering with the Service, you thereby agree to the rules of our site. </li>',
                    t8 : 'The rights.',
                    b8 : '<li> The exclusive right to the Service belongs to the Service. </li> <li> All rights to the materials presented on our website belong to the Rights Holders. </li>'
                },
                lvl : {
                    t1 : 'Your level:',
                    t2 : 'Level',
                    toup : 'To increase the level you need deposit:'
                },
                skins : {
                    title : 'Cashout skins',
                    list : 'Items',
                    hl : 'High to Low',
                    lh : 'Low to High',
                    all : 'All',
                    total : 'Total',
                    buy : 'Buy',
                    buy2 : 'Please wait..',
                    search : 'Enter text to search',
                    trade1 : 'Enter the link to the Steam Trade',
                    trade2 : 'Enter the SteamID64 account on which you are using OPSkins',
                    realTrade : 'Enter your shipping address',
                    more : 'Load more',
                    accept : 'Agree',
                    wait : 'Please wait..',
                    send_info: 'Information to send',
                    send_info2: 'Enter the correct data, otherwise you can not get the goods!',
                    fio: 'Full Name',
                    fio2: 'Full name',
                    adres: 'Delivery address',
                    index: 'Postcode',
                    index2: 'Code',
                    phone: 'Phone number',
                    phone2: 'Phone'
                },
                auth : {
                    auth : 'Sign In',
                    reg : 'Sign Up',
                    login : 'Username',
                    password : 'Password',
                    password2 : 'Repeat password',
                    authbtn : 'Sign In',
                    regbtn : 'Sign Up',
                    wait : 'Please wait..',
                    t : 'SIGN IN WITH SOCIAL',
                    d1 : 'By logging in, you confirm that you are 18 years old and accept the terms of the <a href="/terms" rel="popup" target="_blank" style="color: #4348887d;"> user agreement.',
                    d2  : '* SITE SERVICES ARE THE IMITATOR (SIMULATOR) THAT ALLOWS TO RECEIVE A PSYCHO-EMOTIONAL SATISFACTION WITHOUT ANYTHING'
                }
            }
        });
    });
}